### ISSUE TITLE
Is inveigh mitigated when using Constrained Language Mode?

### ISSUE THREAD

**Issue by dimpol** [Kevin-Robertson/Inveigh#10]
Hi @Kevin-Robertson 
Do you by any chance remember is Inveigh is affected/mitigated when Constrained Language Mode is configured?

Thank you in advance

**Comment by Kevin-Robertson** [comment]
Hi, I haven't done much testing in constrained language mode. Inveigh makes heavy use of a lot of stuff that would be blocked though. I just ran a quick test and a lot of errors were generated on startup.

**Comment by dimpol** [comment]
@Kevin-Robertson Thank you very much for your time to test this... 
My testing resulted in the same outcome...
Closing this and thanks again
