### ISSUE TITLE
Feature Request - WebDAV Support

### ISSUE THREAD

**Issue by mubix** [Kevin-Robertson/Inveigh#23]
As discussed here: https://github.com/NetSPI/PowerUpSQL/issues/54

It would be nice to have support for WebDAV in the cases where this is possible.

**Comment by Kevin-Robertson** [comment]
Sorry, for the delay. This ended up getting caught up in an issue I submitted to MSRC. I now have WebDAV support on the C# side with the Inveigh 2.0 release. I'm also working on rolling everything into a class library. Hopefully that will also make it easier for other tools to take on some of this functionality without needing all of Inveigh.

I don't yet have anything for PowerShell. I'm really having a tough time going back and working with it :)

**Comment by mubix** [comment]
Understood, and thanks! :)
