### ISSUE TITLE
Unhandled Exception: System.ArgumentException: Invalid Parameter "LISTENERIP"

### ISSUE THREAD

**Issue by sp00ks-git** [Kevin-Robertson/Inveigh#36]
I want to set a specific IP to listen on.
After building Inveigh, I notice that the "-ListenerIP" option doesn't seem to be recognised.   

I read in the readme:

" -ListenerIP     Default=Any: IP address for all listeners."

C:\ .\Inveigh.exe -ListenerIP "192.168.1.1"

Unhandled Exception: System.ArgumentException: Invalid Parameter
Parameter name: -LISTENERIP
   at Inveigh.Program.Main(String[] args)

**Comment by sp00ks-git** [comment]
Yes some did some didnt. Havent got the box up in front of me but will check and confirm.
Where is "ListenerIP" reference in the code, i couldn't see it?

**Comment by Kevin-Robertson** [comment]
It's in Program.cs. Maybe you are working with an older version? ListenerIP and others were added in 2.0.

**Comment by sp00ks-git** [comment]
Ah yes, looks like I was using an older version - thanks for confirming.
