### ISSUE TITLE
Documentation is incorrect for "-FileOutput Default=Disabled:" 

### ISSUE THREAD

**Issue by TheKevinWang** [Kevin-Robertson/Inveigh#45]
Default is enabled not disabled. 
https://github.com/Kevin-Robertson/Inveigh/blob/a07a71c0d4ae86d07f58cfbc1e97b48e228f11dc/Inveigh/Program.cs#L28C1-L28C50

**Comment by Kevin-Robertson** [comment]
Thanks! It's fixed now. Note for the PowerShell version it is indeed disabled by default.
