### ISSUE TITLE
Shows "HTTP Capture Disabled Due To In Use Port 80" when actually listening on Port 8081 

### ISSUE THREAD

**Issue by 6cyril** [Kevin-Robertson/Inveigh#8]
Good day, 

As titled, Invoke-Inveigh shows port 80 is listening while there is another service listening on port 0.0.0.0:8081. It happens to be lines on **netstat** that matches "0.0.0.0:8081" with searchstring "0.0.0.0:80". Same issue potentially appears in other netstat commands in the same project.

On line 555 of Inveigh.ps1 
`$HTTP_port_check = netstat -anp TCP | findstr 0.0.0.0:80`

Suggest to update as below to grep the **space** at the end with findstr:
`netstat -anp TCP | findstr LISTENING | findstr /C:":80 "`
or
`netstat -anp TCP | findstr LISTENING | findstr /C:"0.0.0.0:80 "`

Thanks
Cyril

**Comment by Kevin-Robertson** [comment]
Thanks!, I'll get the checks fixed tonight.

**Comment by Kevin-Robertson** [comment]
I added in your netstat fixes. I also added the StartupChecks parameter to allow disabling all checks in the event that any of them get in the way. Thanks again!
